/**
 * Field-ownership index — GENERATED by scripts/gen-field-index.mjs. Do not edit.
 *
 * Maps a transaction field name to the set of transaction types that accept
 * it. `assertKnownFields` rejects a field only when it is listed here AND
 * absent for the transaction being built, so a field this library does not
 * model yet still passes. See Bug #11 in 173-xrpjson-testing.
 *
 * GENERATED FILE — run `node scripts/gen-field-index.mjs` after changing any
 * factory's props interface. `field-index.assert.ts` fails the build if this
 * table drifts from the interfaces it was generated from.
 *
 * Merged from this library's 79 props interfaces and the protocol's own
 * `TRANSACTION_FORMATS` table (ripple-binary-codec@2.11.0). The merge
 * can only widen a field's accepted-type set, never narrow it, so no
 * transaction that accepts a field today can start rejecting it.
 */
import { ValidationError } from '../errors.js';

/**
 * Fields valid on every transaction type, so they own no entry in
 * {@link FIELD_OWNERS}: such an entry would list all 79 types and could never
 * reject anything. Excluding them is what keeps the forward-compatibility hatch
 * working for them, and what makes the completeness assertion in
 * `field-index.assert.ts` usable.
 *
 * The union of the base fields every factory inherits and the codec's
 * `TRANSACTION_FORMATS.common` pseudo-type. The codec list carries fields this
 * library does not inherit — `PreviousTxnID`, `OperationLimit`, and
 * `Sponsor`/`SponsorFlags`/`SponsorSignature`, the last three of which
 * SponsorshipTransfer declares directly. Without them `payment({ Sponsor })`
 * would be rejected as a SponsorshipTransfer-only field.
 */
export const COMMON_FIELDS = [
  'Account',
  'AccountTxnID',
  'Delegate',
  'Fee',
  'Flags',
  'LastLedgerSequence',
  'Memos',
  'NetworkID',
  'OperationLimit',
  'PreviousTxnID',
  'Sequence',
  'Signers',
  'SigningPubKey',
  'SourceTag',
  'Sponsor',
  'SponsorFlags',
  'SponsorSignature',
  'TicketSequence',
  'TransactionType',
  'TxnSignature',
] as const;

/** One of the fields valid on every transaction type. */
export type CommonField = (typeof COMMON_FIELDS)[number];

/**
 * Transaction types that accept each field. Built from 143 field
 * names (322 field/type pairs; 87 fields valid on exactly
 * one type), unioned across the 79 `XxxProps` interfaces and the protocol's
 * `TRANSACTION_FORMATS`.
 *
 * Typed with `satisfies`, NOT `Record<string, …>`. A `Record` annotation
 * adds an index signature, which collapses `keyof` to `string` and silently
 * disarms the assertions in `field-index.assert.ts`.
 */
export const FIELD_OWNERS = {
  AcceptedCredentials: new Set(['PermissionedDomainSet'] as const),
  Amount: new Set(['AMMClawback', 'AMMCreate', 'AMMDeposit', 'AMMWithdraw', 'CheckCash', 'Clawback', 'EscrowCreate', 'LoanBrokerCoverClawback', 'LoanBrokerCoverDeposit', 'LoanBrokerCoverWithdraw', 'LoanPay', 'NFTokenCreateOffer', 'NFTokenMint', 'Payment', 'PaymentChannelClaim', 'PaymentChannelCreate', 'PaymentChannelFund', 'VaultClawback', 'VaultDeposit', 'VaultWithdraw', 'XChainAccountCreateCommit', 'XChainAddAccountCreateAttestation', 'XChainAddClaimAttestation', 'XChainClaim', 'XChainCommit'] as const),
  Amount2: new Set(['AMMCreate', 'AMMDeposit', 'AMMWithdraw'] as const),
  AmountCommitment: new Set(['ConfidentialMPTSend'] as const),
  Asset: new Set(['AMMBid', 'AMMClawback', 'AMMDelete', 'AMMDeposit', 'AMMVote', 'AMMWithdraw', 'VaultCreate'] as const),
  Asset2: new Set(['AMMBid', 'AMMClawback', 'AMMDelete', 'AMMDeposit', 'AMMVote', 'AMMWithdraw'] as const),
  AssetClass: new Set(['OracleSet'] as const),
  AssetScale: new Set(['MPTokenIssuanceCreate'] as const),
  AssetsMaximum: new Set(['VaultCreate', 'VaultSet'] as const),
  AttestationRewardAccount: new Set(['XChainAddAccountCreateAttestation', 'XChainAddClaimAttestation'] as const),
  AttestationSignerAccount: new Set(['XChainAddAccountCreateAttestation', 'XChainAddClaimAttestation'] as const),
  AuditorEncryptedAmount: new Set(['ConfidentialMPTConvert', 'ConfidentialMPTConvertBack', 'ConfidentialMPTSend'] as const),
  AuditorEncryptionKey: new Set(['MPTokenIssuanceSet'] as const),
  AuthAccounts: new Set(['AMMBid'] as const),
  Authorize: new Set(['DelegateSet', 'DepositPreauth'] as const),
  AuthorizeCredentials: new Set(['DepositPreauth'] as const),
  Balance: new Set(['PaymentChannelClaim'] as const),
  BalanceCommitment: new Set(['ConfidentialMPTConvertBack', 'ConfidentialMPTSend'] as const),
  BatchSigners: new Set(['Batch'] as const),
  BidMax: new Set(['AMMBid'] as const),
  BidMin: new Set(['AMMBid'] as const),
  BlindingFactor: new Set(['ConfidentialMPTConvert', 'ConfidentialMPTConvertBack'] as const),
  BookDirectory: new Set(['LedgerStateFix'] as const),
  CancelAfter: new Set(['EscrowCreate', 'PaymentChannelCreate'] as const),
  Channel: new Set(['PaymentChannelClaim', 'PaymentChannelFund'] as const),
  CheckID: new Set(['CheckCancel', 'CheckCash'] as const),
  ClearFlag: new Set(['AccountSet'] as const),
  CloseInterestRate: new Set(['LoanSet'] as const),
  ClosePaymentFee: new Set(['LoanSet'] as const),
  Condition: new Set(['EscrowCreate', 'EscrowFinish'] as const),
  Counterparty: new Set(['LoanSet'] as const),
  CounterpartySignature: new Set(['LoanSet'] as const),
  CounterpartySponsor: new Set(['SponsorshipSet'] as const),
  CoverRateLiquidation: new Set(['LoanBrokerSet'] as const),
  CoverRateMinimum: new Set(['LoanBrokerSet'] as const),
  CredentialIDs: new Set(['AccountDelete', 'ConfidentialMPTSend', 'EscrowFinish', 'LoanBrokerCoverWithdraw', 'Payment', 'PaymentChannelClaim', 'VaultWithdraw'] as const),
  CredentialType: new Set(['CredentialAccept', 'CredentialCreate', 'CredentialDelete'] as const),
  Data: new Set(['DIDSet', 'LoanBrokerSet', 'LoanSet', 'VaultCreate', 'VaultSet'] as const),
  DebtMaximum: new Set(['LoanBrokerSet'] as const),
  DeliverMin: new Set(['CheckCash', 'Payment'] as const),
  Destination: new Set(['AccountDelete', 'CheckCreate', 'ConfidentialMPTSend', 'EscrowCreate', 'LoanBrokerCoverWithdraw', 'NFTokenCreateOffer', 'NFTokenMint', 'Payment', 'PaymentChannelCreate', 'VaultWithdraw', 'XChainAccountCreateCommit', 'XChainAddAccountCreateAttestation', 'XChainAddClaimAttestation', 'XChainClaim'] as const),
  DestinationEncryptedAmount: new Set(['ConfidentialMPTSend'] as const),
  DestinationTag: new Set(['AccountDelete', 'CheckCreate', 'ConfidentialMPTSend', 'EscrowCreate', 'LoanBrokerCoverWithdraw', 'Payment', 'PaymentChannelCreate', 'VaultWithdraw', 'XChainClaim'] as const),
  DIDDocument: new Set(['DIDSet'] as const),
  Domain: new Set(['AccountSet'] as const),
  DomainID: new Set(['MPTokenIssuanceCreate', 'MPTokenIssuanceSet', 'OfferCreate', 'Payment', 'PermissionedDomainDelete', 'PermissionedDomainSet', 'VaultCreate', 'VaultSet'] as const),
  EmailHash: new Set(['AccountSet'] as const),
  EPrice: new Set(['AMMDeposit', 'AMMWithdraw'] as const),
  Expiration: new Set(['CheckCreate', 'CredentialCreate', 'NFTokenCreateOffer', 'NFTokenMint', 'OfferCreate', 'PaymentChannelFund'] as const),
  FeeAmountDelta: new Set(['SponsorshipSet'] as const),
  FinishAfter: new Set(['EscrowCreate'] as const),
  Fulfillment: new Set(['EscrowFinish'] as const),
  GracePeriod: new Set(['LoanSet'] as const),
  Holder: new Set(['AMMClawback', 'Clawback', 'ConfidentialMPTClawback', 'MPTokenAuthorize', 'MPTokenIssuanceSet', 'VaultClawback'] as const),
  HolderEncryptedAmount: new Set(['ConfidentialMPTConvert', 'ConfidentialMPTConvertBack'] as const),
  HolderEncryptionKey: new Set(['ConfidentialMPTConvert'] as const),
  ImmutableFlags: new Set(['MPTokenIssuanceCreate', 'MPTokenIssuanceSet'] as const),
  InterestRate: new Set(['LoanSet'] as const),
  InvoiceID: new Set(['CheckCreate', 'Payment'] as const),
  Issuer: new Set(['CredentialAccept', 'CredentialDelete', 'NFTokenMint'] as const),
  IssuerEncryptedAmount: new Set(['ConfidentialMPTConvert', 'ConfidentialMPTConvertBack', 'ConfidentialMPTSend'] as const),
  IssuerEncryptionKey: new Set(['MPTokenIssuanceSet'] as const),
  LastUpdateTime: new Set(['OracleSet'] as const),
  LateInterestRate: new Set(['LoanSet'] as const),
  LatePaymentFee: new Set(['LoanSet'] as const),
  LedgerFixType: new Set(['LedgerStateFix'] as const),
  LimitAmount: new Set(['TrustSet'] as const),
  LoanBrokerID: new Set(['LoanBrokerCoverClawback', 'LoanBrokerCoverDeposit', 'LoanBrokerCoverWithdraw', 'LoanBrokerDelete', 'LoanBrokerSet', 'LoanSet'] as const),
  LoanID: new Set(['LoanDelete', 'LoanManage', 'LoanPay'] as const),
  LoanOriginationFee: new Set(['LoanSet'] as const),
  LoanServiceFee: new Set(['LoanSet'] as const),
  LPTokenIn: new Set(['AMMWithdraw'] as const),
  LPTokenOut: new Set(['AMMDeposit'] as const),
  ManagementFeeRate: new Set(['LoanBrokerSet'] as const),
  MaxFee: new Set(['SponsorshipSet'] as const),
  MaximumAmount: new Set(['MPTokenIssuanceCreate'] as const),
  MemoData: new Set(['VaultDelete'] as const),
  MessageKey: new Set(['AccountSet'] as const),
  MinAccountCreateAmount: new Set(['XChainCreateBridge', 'XChainModifyBridge'] as const),
  MPTAmount: new Set(['ConfidentialMPTClawback', 'ConfidentialMPTConvert', 'ConfidentialMPTConvertBack'] as const),
  MPTokenIssuanceID: new Set(['ConfidentialMPTClawback', 'ConfidentialMPTConvert', 'ConfidentialMPTConvertBack', 'ConfidentialMPTMergeInbox', 'ConfidentialMPTSend', 'MPTokenAuthorize', 'MPTokenIssuanceDestroy', 'MPTokenIssuanceSet'] as const),
  MPTokenMetadata: new Set(['MPTokenIssuanceCreate', 'MPTokenIssuanceSet', 'VaultCreate'] as const),
  NFTokenBrokerFee: new Set(['NFTokenAcceptOffer'] as const),
  NFTokenBuyOffer: new Set(['NFTokenAcceptOffer'] as const),
  NFTokenID: new Set(['NFTokenBurn', 'NFTokenCreateOffer', 'NFTokenModify'] as const),
  NFTokenMinter: new Set(['AccountSet'] as const),
  NFTokenOffers: new Set(['NFTokenCancelOffer'] as const),
  NFTokenSellOffer: new Set(['NFTokenAcceptOffer'] as const),
  NFTokenTaxon: new Set(['NFTokenMint'] as const),
  ObjectID: new Set(['SponsorshipTransfer'] as const),
  OfferSequence: new Set(['EscrowCancel', 'EscrowFinish', 'OfferCancel', 'OfferCreate'] as const),
  OracleDocumentID: new Set(['OracleDelete', 'OracleSet'] as const),
  OtherChainDestination: new Set(['XChainCommit'] as const),
  OtherChainSource: new Set(['XChainAddAccountCreateAttestation', 'XChainAddClaimAttestation', 'XChainCreateClaimID'] as const),
  OverpaymentFee: new Set(['LoanSet'] as const),
  OverpaymentInterestRate: new Set(['LoanSet'] as const),
  Owner: new Set(['EscrowCancel', 'EscrowFinish', 'LedgerStateFix', 'NFTokenBurn', 'NFTokenCreateOffer', 'NFTokenModify'] as const),
  Paths: new Set(['Payment'] as const),
  PaymentInterval: new Set(['LoanSet'] as const),
  PaymentTotal: new Set(['LoanSet'] as const),
  Permissions: new Set(['DelegateSet'] as const),
  PriceDataSeries: new Set(['OracleSet'] as const),
  PrincipalRequested: new Set(['LoanSet'] as const),
  Provider: new Set(['OracleSet'] as const),
  PublicKey: new Set(['PaymentChannelClaim', 'PaymentChannelCreate', 'XChainAddAccountCreateAttestation', 'XChainAddClaimAttestation'] as const),
  QualityIn: new Set(['TrustSet'] as const),
  QualityOut: new Set(['TrustSet'] as const),
  RawTransactions: new Set(['Batch'] as const),
  RedemptionDate: new Set(['VaultCreate'] as const),
  RegularKey: new Set(['SetRegularKey'] as const),
  RemainingOwnerCountDelta: new Set(['SponsorshipSet'] as const),
  Scale: new Set(['VaultCreate'] as const),
  SenderEncryptedAmount: new Set(['ConfidentialMPTSend'] as const),
  SendMax: new Set(['CheckCreate', 'Payment'] as const),
  SetFlag: new Set(['AccountSet'] as const),
  SettleDelay: new Set(['PaymentChannelCreate'] as const),
  Signature: new Set(['PaymentChannelClaim', 'XChainAddAccountCreateAttestation', 'XChainAddClaimAttestation'] as const),
  SignatureReward: new Set(['XChainAccountCreateCommit', 'XChainAddAccountCreateAttestation', 'XChainCreateBridge', 'XChainCreateClaimID', 'XChainModifyBridge'] as const),
  SignerEntries: new Set(['SignerListSet'] as const),
  SignerQuorum: new Set(['SignerListSet'] as const),
  Sponsee: new Set(['SponsorshipSet', 'SponsorshipTransfer'] as const),
  Subject: new Set(['CredentialCreate', 'CredentialDelete'] as const),
  SubscriptionDate: new Set(['VaultCreate'] as const),
  TakerGets: new Set(['OfferCreate'] as const),
  TakerPays: new Set(['OfferCreate'] as const),
  TicketCount: new Set(['TicketCreate'] as const),
  TickSize: new Set(['AccountSet'] as const),
  TradingFee: new Set(['AMMCreate', 'AMMDeposit', 'AMMVote'] as const),
  TransferFee: new Set(['MPTokenIssuanceCreate', 'MPTokenIssuanceSet', 'NFTokenMint'] as const),
  TransferRate: new Set(['AccountSet'] as const),
  Unauthorize: new Set(['DepositPreauth'] as const),
  UnauthorizeCredentials: new Set(['DepositPreauth'] as const),
  URI: new Set(['CredentialCreate', 'DIDSet', 'NFTokenMint', 'NFTokenModify', 'OracleSet'] as const),
  VaultID: new Set(['LoanBrokerSet', 'VaultClawback', 'VaultDelete', 'VaultDeposit', 'VaultSet', 'VaultWithdraw'] as const),
  VaultKind: new Set(['VaultCreate'] as const),
  WalletLocator: new Set(['AccountSet'] as const),
  WalletSize: new Set(['AccountSet'] as const),
  WasLockingChainSend: new Set(['XChainAddAccountCreateAttestation', 'XChainAddClaimAttestation'] as const),
  WithdrawalPolicy: new Set(['VaultCreate'] as const),
  XChainAccountCreateCount: new Set(['XChainAddAccountCreateAttestation'] as const),
  XChainBridge: new Set(['XChainAccountCreateCommit', 'XChainAddAccountCreateAttestation', 'XChainAddClaimAttestation', 'XChainClaim', 'XChainCommit', 'XChainCreateBridge', 'XChainCreateClaimID', 'XChainModifyBridge'] as const),
  XChainClaimID: new Set(['XChainAddClaimAttestation', 'XChainClaim', 'XChainCommit'] as const),
  ZKProof: new Set(['ConfidentialMPTClawback', 'ConfidentialMPTConvert', 'ConfidentialMPTConvertBack', 'ConfidentialMPTSend'] as const),
} satisfies Record<string, ReadonlySet<string>>;

/**
 * Reject a field that belongs to a different transaction type.
 *
 * A key with no entry in `FIELD_OWNERS` is a field the library does not model
 * yet — the forward-compatibility hatch at `BaseTransactionFields` — and is
 * allowed through. Only a key that is known AND wrong for this type is
 * refused, with the transaction that does accept it named in the message.
 *
 * @param txType - The transaction type literal being built.
 * @param field  - The prop key to check.
 * @throws {ValidationError} if `field` belongs to a different transaction.
 */
export function assertKnownFields(txType: string, field: string): void {
  // The lookup is deliberately widened: `field` is a runtime string that a
  // JavaScript caller controls, so it is not one of the table's literal keys.
  // A key that is not in the table at all resolves to undefined here, which is
  // the forward-compatibility case below.
  const owners = (FIELD_OWNERS as Readonly<Record<string, ReadonlySet<string>>>)[field];
  if (owners === undefined) return; // unmodelled field — forward-compat
  if (owners.has(txType)) return;   // correct transaction
  throw new ValidationError(
    `${txType}: "${field}" is not a field on this transaction. ` +
      `It belongs to: ${[...owners].sort().join(', ')}.`,
  );
}
